import type { ToolbarCategory } from "@/types/workbench";

export const toolbarCategories: ToolbarCategory[] = [
  {
    id: "glassware",
    label: "Glassware",
    description: "Core containers for standards and samples.",
    items: [
      {
        id: "volumetric_flask",
        itemType: "tool",
        name: "Volumetric flask",
        subtitle: "100 mL calibration prep",
        description: "Build standard dilutions with a fixed final volume.",
        accent: "sky",
        toolType: "volumetric_flask",
        capacity_ml: 100,
        accepts_liquids: true,
      },
      {
        id: "amber_bottle",
        itemType: "tool",
        name: "Amber bottle",
        subtitle: "Light-sensitive storage",
        description: "Hold stock solutions or reagents between prep steps.",
        accent: "amber",
        toolType: "amber_bottle",
        capacity_ml: 250,
        accepts_liquids: true,
      },
      {
        id: "sample_vial",
        itemType: "tool",
        name: "Sample vial",
        subtitle: "Autosampler ready",
        description: "Transfer the prepared solution into the rack sequence.",
        accent: "emerald",
        toolType: "sample_vial",
        capacity_ml: 2,
        accepts_liquids: true,
      },
      {
        id: "beaker",
        itemType: "tool",
        name: "Beaker",
        subtitle: "Open handling vessel",
        description: "Useful for quick transfers, rinses, and waste collection.",
        accent: "rose",
        toolType: "beaker",
        capacity_ml: 250,
        accepts_liquids: true,
      },
    ],
  },
  {
    id: "liquids",
    label: "Liquids",
    description: "Solvents and matrices available on the bench.",
    items: [
      {
        id: "ultrapure_water",
        itemType: "liquid",
        name: "Ultrapure water",
        subtitle: "Aqueous phase",
        description: "Diluent and rinse solvent for low-organic preparations.",
        accent: "sky",
        liquidType: "ultrapure_water",
        transfer_volume_ml: 10,
      },
      {
        id: "acetonitrile",
        itemType: "liquid",
        name: "Acetonitrile",
        subtitle: "Organic modifier",
        description: "Common LC solvent for sample prep and rinsing.",
        accent: "amber",
        liquidType: "acetonitrile",
        transfer_volume_ml: 10,
      },
      {
        id: "methanol",
        itemType: "liquid",
        name: "Methanol",
        subtitle: "Alternative organic solvent",
        description: "Useful for extraction or stronger wash steps.",
        accent: "emerald",
        liquidType: "methanol",
        transfer_volume_ml: 10,
      },
      {
        id: "formic_acid",
        itemType: "liquid",
        name: "Formic acid",
        subtitle: "0.1% acidifier",
        description: "Supports ionization and stabilizes acidic mobile phases.",
        accent: "rose",
        liquidType: "formic_acid",
        transfer_volume_ml: 1,
      },
      {
        id: "matrix_blank",
        itemType: "liquid",
        name: "Matrix blank",
        subtitle: "Control background",
        description: "Represents the biological matrix before analyte addition.",
        accent: "sky",
        liquidType: "matrix_blank",
        transfer_volume_ml: 10,
      },
    ],
  },
];
